name: Cypress Tests

on: 
    push:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to run the tests'
                required: true
                type: choice
                options:
                - dev
                - qa

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies in root
        run: npm install

      - name: Start Nex app
        run: npm run dev &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3000'
          spec: 'cypress/e2e/search.cy.js'
